lightning_module:
  type: Sparse4D
  scheduler:
    type: StepLR
    step_size: 10
    gamma: 0.1
  optimizer:
    type: AdamW
    lr: 0.001
    weight_decay: 0.0001
  loss:
    type: Sparse4DLoss
    loss_cls:
      type: FocalLoss
      alpha: 0.25
      gamma: 2.0
    loss_reg:
      type: SmoothL1Loss
      beta: 1.0
  model_cfg:
    detector:
      type: Sparse4DDetector
      backbone:
        type: ResNet
        depth: 50
      neck:
        type: FPN
        in_channels:
        - 256
        - 512
        - 1024
        - 2048
        out_channels: 256
        start_level: 1
        add_extra_convs: on_output
      head:
        type: Sparse4DHead
        in_channels: 256
        out_channels: 256
        num_classes: 10
